version: "3.9"

services:
  back:
    build:
      context: ./go
      dockerfile: Dockerfile.dev
    env_file:
      - ./go/.env
    ports:
      - "8888:8888"
    volumes:
      - ./go:/app
      - go_mod_cache:/go/pkg/mod

  front:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    environment:
      VITE_API_PROXY_TARGET: http://back:8888
    ports:
      - "8080:8080"
    volumes:
      - ./front:/app
      - front_node_modules:/app/node_modules
    depends_on:
      - back

  mailtrap:
    image: axllent/mailpit:latest
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  go_mod_cache:
  front_node_modules:
